import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
fs.mkdirSync('.test-build',{recursive:true});
for(const name of ['model','actions']){
 const source=fs.readFileSync(`lib/tovant/${name}.ts`,'utf8');
 const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("from './model'","from './model.mjs'");
 fs.writeFileSync(`.test-build/${name}.mjs`,out);
}
const {seed,available,day}=await import('../.test-build/model.mjs');
const {applyAction}=await import('../.test-build/actions.mjs');
let count=0;function test(name,fn){fn();count++;console.log(`PASS ${name}`);}
const action=(type,role,providerId,jobId,data={})=>({type,role,actor:role==='customer'?'sam':role,providerId,jobId,data});
const booking=(p,overrides={})=>({serviceId:p.services[0].id,customerId:'sam',vehicleId:'audi',date:day(10),time:'09:00',staff:p.staff[0],address:'123 Demo Avenue, Minneapolis',zip:'55407',notes:'Test booking',seller:'Taylor, 612-555-0123',destination:'On-site assistance',...overrides});
test('Fixed booking persists one linked customer/provider job and reserves staff',()=>{let s=seed();const p=s.providers.find(p=>p.id==='southpaw');s=applyAction(s,action('book','customer',p.id,undefined,booking(p)));assert.equal(s.jobs[0].status,'scheduled');assert.equal(s.jobs[0].customerId,'sam');assert.equal(s.jobs[0].providerId,p.id);assert.equal(s.jobs[0].vehicleId,'audi');assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p))),/unavailable/);s.vehicles.push({...s.vehicles[0],id:'second'});assert.doesNotThrow(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{staff:'Jordan',vehicleId:'second'}))));});
test('Repair must be approved by customer before work can start',()=>{let s=seed();let j=s.jobs.find(j=>j.id==='TV-1001');assert.throws(()=>applyAction(s,action('transition','provider','ridgeline',j.id,{status:'in_progress'})),/cannot/);assert.throws(()=>applyAction(s,action('transition','provider','ridgeline',j.id,{status:'scheduled'})),/customer workspace/);s=applyAction(s,action('transition','customer','ridgeline',j.id,{status:'scheduled'}));j=s.jobs.find(j=>j.id==='TV-1001');assert.ok(j.approvedAt);s=applyAction(s,action('transition','provider','ridgeline',j.id,{status:'in_progress'}));s=applyAction(s,action('transition','provider','ridgeline',j.id,{status:'completed'}));s=applyAction(s,action('pay','provider','ridgeline',j.id));assert.ok(s.jobs.find(j=>j.id==='TV-1001').paidAt);assert.throws(()=>applyAction(s,action('pay','provider','ridgeline','TV-1001')),/unpaid/);});
test('Itemized estimate has exact total and immutable booked service price',()=>{let s=seed();s=applyAction(s,action('estimate','provider','ridgeline','TV-1001',{lines:[{description:'Parts',quantity:2,price:95.50},{description:'Labor',quantity:1.5,price:120}]}));assert.equal(s.jobs.find(j=>j.id==='TV-1001').total,371);assert.equal(s.jobs.find(j=>j.id==='TV-1001').status,'awaiting_approval');const p=s.providers.find(p=>p.id==='ridgeline');s=applyAction(s,action('service','provider',p.id,undefined,{...p.services[0],price:999}));assert.equal(s.jobs.find(j=>j.id==='TV-1001').service.price,120);});
test('Inspection cannot complete until all six findings are published',()=>{let s=seed();s=applyAction(s,action('transition','provider','preflight','TV-1005',{status:'scheduled'}));s=applyAction(s,action('transition','provider','preflight','TV-1005',{status:'en_route'}));s=applyAction(s,action('transition','provider','preflight','TV-1005',{status:'arrived'}));s=applyAction(s,action('transition','provider','preflight','TV-1005',{status:'in_progress'}));assert.throws(()=>applyAction(s,action('transition','provider','preflight','TV-1005',{status:'completed'})),/report/);const {inspectionAreas}=awaitDummy();const findings=inspectionAreas.map(area=>({area,condition:'Good',note:'Inspected, no concern observed.'}));s=applyAction(s,action('report','provider','preflight','TV-1005',{findings}));s=applyAction(s,action('transition','provider','preflight','TV-1005',{status:'completed'}));assert.equal(s.jobs.find(j=>j.id==='TV-1005').status,'completed');});
function awaitDummy(){return {inspectionAreas:['Exterior & body','Tires & brakes','Engine & fluids','Electrical & diagnostics','Interior & safety','Road test']};}
test('Dispatch proceeds through en route and on site',()=>{let s=seed();const p=s.providers.find(p=>p.id==='northstar');s=applyAction(s,action('book','customer',p.id,undefined,booking(p)));const id=s.jobs[0].id;for(const status of ['scheduled','en_route','arrived','completed'])s=applyAction(s,action('transition','provider',p.id,id,{status}));assert.equal(s.jobs[0].status,'completed');});
test('Job messages and actions are isolated by business and customer',()=>{const s=seed();assert.throws(()=>applyAction(s,action('message','provider','southpaw','TV-1001',{text:'Wrong shop'})),/another business/);assert.throws(()=>applyAction(s,action('message','customer','ridgeline','TV-1002',{text:'Wrong customer'})),/another customer/);const next=applyAction(s,action('message','customer','ridgeline','TV-1001',{text:'Thanks!'}));assert.equal(next.jobs.find(j=>j.id==='TV-1001').messages.length,2);assert.equal(next.jobs.find(j=>j.id==='TV-1002').messages.length,0);});
test('Booking rejects wrong vehicles, invalid service and out-of-pilot location',()=>{const s=seed(),p=s.providers.find(p=>p.id==='southpaw');assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{vehicleId:'toyota'}))),/belonging/);assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{zip:'10001'}))),/pilot/);assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{serviceId:'fake'}))),/available service/);});
test('Scheduling protects working hours, buffers and blocked time',()=>{let s=seed(),p=s.providers.find(p=>p.id==='southpaw');assert.equal(available(s,p,day(10),'17:30',120,'Alex'),false);assert.equal(available(s,p,'2026-02-30','09:00',120,'Alex'),false);s=applyAction(s,action('block','provider',p.id,undefined,{date:day(10),time:'12:00',staff:'Alex',duration:60}));assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{time:'10:00'}))),/unavailable/);assert.doesNotThrow(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{time:'09:00'}))));});
test('Cancellation releases appointment and is forbidden after work starts',()=>{let s=seed(),p=s.providers.find(p=>p.id==='southpaw');s=applyAction(s,action('book','customer',p.id,undefined,booking(p)));let id=s.jobs[0].id;s=applyAction(s,action('transition','customer',p.id,id,{status:'cancelled',reason:'Plans changed'}));assert.equal(available(s,p,day(10),'09:00',120,'Alex'),true);assert.throws(()=>applyAction(s,action('transition','provider','ridgeline','TV-1003',{status:'cancelled'})),/Work has started/);});
test('Only completed jobs can be reviewed and each has one review',()=>{let s=seed();assert.throws(()=>applyAction(s,action('review','customer','ridgeline','TV-1001',{rating:5,text:'Great'})),/completed/);s=applyAction(s,action('transition','customer','ridgeline','TV-1001',{status:'scheduled'}));s=applyAction(s,action('transition','provider','ridgeline','TV-1001',{status:'in_progress'}));s=applyAction(s,action('transition','provider','ridgeline','TV-1001',{status:'completed'}));s=applyAction(s,action('review','customer','ridgeline','TV-1001',{rating:5,text:'Clear and helpful.'}));assert.throws(()=>applyAction(s,action('review','customer','ridgeline','TV-1001',{rating:5,text:'Duplicate'})),/once/);});
test('Onboarding requires review before a business can receive requests',()=>{let s=seed();s=applyAction(s,action('onboard','customer',undefined,undefined,{name:'New Demo Garage',area:'Minneapolis',zip:'55407',mobile:false,category:'Mechanics & mobile',workflow:'estimate',serviceName:'Diagnosis',price:100,duration:60}));let p=s.providers.at(-1);assert.equal(p.verified,false);assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p))),/not taking/);s=applyAction(s,action('verify','admin',p.id,undefined,{verified:true}));assert.doesNotThrow(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p))));});
test('Support tickets preserve customer record and admin resolution',()=>{let s=seed();s=applyAction(s,action('ticket','customer',undefined,undefined,{subject:'Booking help',text:'Please help with the demo.'}));const t=s.tickets[0];assert.equal(t.customerId,'sam');assert.throws(()=>applyAction(s,action('ticket_reply','customer',undefined,undefined,{id:t.id,reply:'Done'})),/admin workspace/);s=applyAction(s,action('ticket_reply','admin',undefined,undefined,{id:t.id,reply:'Resolved.'}));assert.equal(s.tickets[0].status,'Resolved');});
test('Same vehicle cannot overlap across different providers',()=>{let s=seed();const p=s.providers.find(p=>p.id==='southpaw');s=applyAction(s,action('book','customer',p.id,undefined,booking(p)));const q=s.providers.find(p=>p.id==='washlane');assert.throws(()=>applyAction(s,action('book','customer',q.id,undefined,booking(q))),/unavailable/);});
test('Mobile detail has travel stages and cannot finish on arrival',()=>{let s=seed();const p=s.providers.find(p=>p.id==='washlane');s=applyAction(s,action('book','customer',p.id,undefined,booking(p)));const id=s.jobs[0].id;assert.throws(()=>applyAction(s,action('transition','provider',p.id,id,{status:'in_progress'})),/cannot/);for(const status of ['en_route','arrived'])s=applyAction(s,action('transition','provider',p.id,id,{status}));assert.throws(()=>applyAction(s,action('transition','provider',p.id,id,{status:'completed'})),/cannot/);for(const status of ['in_progress','completed'])s=applyAction(s,action('transition','provider',p.id,id,{status}));assert.equal(s.jobs[0].status,'completed');});
test('Provider rescheduling an approved repair requires renewed customer approval',()=>{let s=seed();s=applyAction(s,action('transition','customer','ridgeline','TV-1001',{status:'scheduled'}));s=applyAction(s,action('reschedule','provider','ridgeline','TV-1001',{date:day(11),time:'10:00',staff:'Alex'}));const j=s.jobs.find(j=>j.id==='TV-1001');assert.equal(j.status,'awaiting_approval');assert.equal(j.approvedAt,undefined);});
test('Full draft details survive saving and are removed on successful booking',()=>{let s=seed();const p=s.providers.find(p=>p.id==='southpaw');const b=booking(p);s=applyAction(s,action('draft','customer',p.id,undefined,b));const draft=s.drafts[0];assert.equal(draft.customerId,'sam');assert.equal(draft.date,b.date);assert.equal(draft.address,b.address);s=applyAction(s,action('book','customer',p.id,undefined,{...b,draftId:draft.id}));assert.equal(s.drafts.length,0);});
test('Mobile demo radius is enforced for the supported demo location',()=>{let s=seed();const p=s.providers.find(p=>p.id==='harlan');p.radius=1;assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p))),/radius/);assert.throws(()=>applyAction(s,action('book','customer',p.id,undefined,booking(p,{zip:'55199'}))),/coverage/);});
test('Photo metadata stays with the authorized job',()=>{let s=seed();assert.throws(()=>applyAction(s,action('photo','provider','southpaw','TV-1001',{key:'demo/photo.jpg',caption:'Brake pads'})),/another business/);s=applyAction(s,action('photo','customer','ridgeline','TV-1001',{key:'demo/photo.jpg',caption:'Brake pads'}));assert.equal(s.jobs.find(j=>j.id==='TV-1001').photos.length,1);});
console.log(`\n${count} domain tests passed.`);
