'use client';
import { useEffect,useRef,useState,type ComponentType } from 'react';
import { LoaderCircle } from 'lucide-react';
import { Toaster,toast } from 'sonner';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Demo } from './context';
import { Button } from './ui';
import type { State,Role } from '@/lib/tovant/model';
import type { Action } from '@/lib/tovant/actions';
export default function Tovant(){
 const [role,setRoleState]=useState<Role>('customer');const [ReferenceUI,setReferenceUI]=useState<ComponentType|null>(null);useEffect(()=>{import('../../reference-ui/App.jsx').then(m=>setReferenceUI(()=>m.default));},[]);const router={push:(to:string)=>{window.location.href=to;}};const [data,setData]=useState<{state:State;revision:number}|null>(null);const dataRef=useRef(data);dataRef.current=data;const roleRef=useRef(role);roleRef.current=role;const setRole=(next:Role)=>{roleRef.current=next;setRoleState(next);};const [providerId,setProvider]=useState('ridgeline');const [customerId,setCustomer]=useState('sam');const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');const [reset,setReset]=useState(false);
 const setProviderId=(id:string)=>{setProvider(id);try{localStorage.setItem('tovant-business-preference',id);}catch{}};
 async function load(){try{const response=await fetch('/api/demo',{cache:'no-store'});const value=await response.json() as {state:State;revision:number;error?:string};if(!response.ok)throw new Error(value.error);setData(value);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load the demo.');}}
 useEffect(()=>{load();try{const id=localStorage.getItem('tovant-business-preference');if(id)setProvider(id);const cid=localStorage.getItem('tovant-customer-preference');if(cid)setCustomer(cid);}catch{}},[]);
 useEffect(()=>{if(data&&!data.state.customers.some(c=>c.id===customerId))setCustomer('sam');},[data,customerId]);
 async function act(type:Action['type'],details:Record<string,unknown>={},jobId?:string,pid?:string){while(lock.current)await new Promise(resolve=>setTimeout(resolve,50));if(!dataRef.current)return false;lock.current=true;setBusy(true);const currentRole=roleRef.current;try{const response=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:dataRef.current.revision,action:{type,role:currentRole,actor:currentRole==='customer'?customerId:currentRole,providerId:pid||providerId,jobId,data:details}})});const value=await response.json() as {state:State;revision:number;error?:string};if(!response.ok){if(value.state)setData({state:value.state,revision:value.revision});throw new Error(value.error);}dataRef.current=value;setData(value);if(type!=='reference')toast.success(type==='message'?'Message saved':type==='book'?'Booking saved':type==='reset'?'Demo reset':'Changes saved');return true;}catch(e){toast.error(e instanceof Error?e.message:'Could not save. Please retry.',{duration:6500});return false;}finally{setBusy(false);lock.current=false;}}
 async function upload(file:File,caption:string,jobId:string,pid:string){while(lock.current)await new Promise(resolve=>setTimeout(resolve,50));if(!dataRef.current)return false;lock.current=true;setBusy(true);try{const form=new FormData();form.set('file',file);form.set('caption',caption);form.set('jobId',jobId);form.set('providerId',pid);form.set('role',roleRef.current);form.set('actor',customerId);form.set('revision',String(dataRef.current.revision));const response=await fetch('/api/media',{method:'POST',body:form});const value=await response.json() as {state:State;revision:number;error?:string};if(!response.ok){if(value.state)setData({state:value.state,revision:value.revision});throw new Error(value.error);}dataRef.current=value;setData(value);toast.success('Photo saved');return true;}catch(e){toast.error(e instanceof Error?e.message:'Photo upload failed');return false;}finally{lock.current=false;setBusy(false);}}
 if(!data)return <main className="loading-screen"><div className="wordmark">tovant<span/></div>{error?<><h1>Let’s reconnect your demo.</h1><p>{error}</p><Button onClick={load}>Retry</Button></>:<><LoaderCircle className="spin" size={28}/><h1>Opening your workspace…</h1><p>Your vehicles, jobs and local experts, together.</p></>}</main>;
 return <Demo.Provider value={{state:data.state,role,customerId,providerId,setProviderId,setCustomerId:setCustomer,setRole,busy,requestReset:()=>setReset(true),act,upload}}>{ReferenceUI?<ReferenceUI/>:<div className="loading-screen">Opening Tovant…</div>}<Toaster position="bottom-right" richColors/><AlertDialog open={reset} onOpenChange={setReset}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset your demo?</AlertDialogTitle><AlertDialogDescription>This removes the jobs, messages, vehicles and settings you created in this demo session and restores the sample data.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep my changes</AlertDialogCancel><Button disabled={busy} onClick={async()=>{if(await act('reset')){setReset(false);setProviderId('ridgeline');setCustomer('sam');try{localStorage.removeItem('tovant-customer-preference');}catch{}router.push('/');}}}>Reset demo</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></Demo.Provider>;
}
