'use client';
import { useState } from 'react';
import { useRouter } from './navigation';
import { Check, Car, CalendarDays, ClipboardCheck } from 'lucide-react';
import { useDemo } from './context';
import { Modal,Field,Choice,Input,Textarea,Button } from './ui';
import { available,day,money,vehicleName,workflowNames,type Provider,type Service,type State } from '@/lib/tovant/model';
export default function Booking({provider,initialService,onClose,initialNotes='',initialDate,draft}:{provider:Provider;initialService?:Service;onClose:()=>void;initialNotes?:string;initialDate?:string;draft?:State['drafts'][number]}){
 const {state,act,busy,role,customerId}=useDemo();const router=useRouter();const [step,setStep]=useState(0);const [serviceId,setService]=useState(initialService?.id||provider.services[0].id);const service=provider.services.find(s=>s.id===serviceId)!;
 const [customer,setCustomer]=useState(customerId);const vehicles=state.vehicles.filter(v=>v.customerId===customer);const [vehicle,setVehicle]=useState(draft?.vehicleId||vehicles[0]?.id||'');const [date,setDate]=useState(draft?.date||initialDate||day(1));const [time,setTime]=useState(draft?.time||'09:00');const [staff,setStaff]=useState(draft?.staff||provider.staff[0]);const [address,setAddress]=useState(draft?.address||'');const [zip,setZip]=useState(draft?.zip||'55407');const [notes,setNotes]=useState(initialNotes);const [seller,setSeller]=useState(draft?.seller||'');const [destination,setDestination]=useState(draft?.destination||'');const [error,setError]=useState('');const [done,setDone]=useState(false);
 const slots=Array.from({length:(provider.close-provider.open)*2},(_,i)=>`${String(provider.open+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`).filter(t=>available(state,provider,date,t,service.duration,staff,'',vehicle));
 const next=()=>{setError('');if(step===1&&(!vehicle||!zip.match(/^\d{5}$/)||(provider.mobile&&!address.trim())||(service.workflow==='inspection'&&!seller.trim())||(service.workflow==='dispatch'&&!destination.trim()))){setError('Complete your vehicle, location and required service details.');return;}if(step===2&&!slots.includes(time)){setError('Choose an available appointment time.');return;}setStep(step+1);};
 async function confirm(){if(await act('book',{serviceId,customerId:customer,vehicleId:vehicle,date,time,staff,address,zip,notes,seller,destination,draftId:draft?.id},undefined,provider.id))setDone(true);}
 return <Modal open onClose={onClose} title={done?'You’re all set':role==='provider'?'Create a booking':`Book with ${provider.name}`} description={done?'Your customer and provider workspaces now share this job.':`${workflowNames[service.workflow]} · ${provider.mobile?'Comes to you':'At the shop'} · No Tovant booking fee`} wide>
 {done?<div className="success"><span className="success-icon"><Check/></span><h2>{service.workflow==='appointment'?'Appointment confirmed':'Request sent'}</h2><p>{service.workflow==='appointment'?`${date} at ${time} with ${staff}.`:'The business will confirm your requested time. Repairs require your written approval before work begins.'}</p><Button onClick={()=>{onClose();router.push(role==='provider'?'/business/jobs':'/jobs');}}>View jobs</Button></div>:<>
 <ol className="steps">{['Service','Vehicle & details','Schedule','Review'].map((s,i)=><li key={s} className={i===step?'current':i<step?'complete':''}><span>{i<step?<Check size={14}/>:i+1}</span>{s}</li>)}</ol>
 {step===0&&<div className="stack">{provider.services.map(s=><button key={s.id} className={`service-option ${serviceId===s.id?'selected':''}`} onClick={()=>setService(s.id)}><div><strong>{s.name}</strong><p>{workflowNames[s.workflow]} · {s.duration} minutes</p></div><strong>{money(s.price)}{s.workflow==='estimate'&&<small> consultation</small>}</strong></button>)}<p className="notice">The listed consultation fee covers assessment only. Any additional repair or custom work requires an approved estimate. Fixed packages use the listed demo price for all vehicle sizes.</p></div>}
 {step===1&&<div className="stack">{role==='provider'&&<Field label="Customer"><Choice value={customer} onChange={v=>{setCustomer(v);setVehicle(state.vehicles.find(x=>x.customerId===v)?.id||'');}} options={state.customers.map(c=>({value:c.id,label:c.name}))}/></Field>}<Field label="Vehicle"><Choice label="Vehicle" value={vehicle} onChange={setVehicle} options={vehicles.map(v=>({value:v.id,label:vehicleName(v)+' · '+v.size}))}/></Field><div className="two-col"><Field label="Service ZIP"><Input value={zip} onChange={e=>setZip(e.target.value)} maxLength={5}/></Field><Field label={provider.mobile?'Service address *':'Drop-off location'}><Input value={address} onChange={e=>setAddress(e.target.value)} placeholder={provider.mobile?'Street address, city':`${provider.area}, Twin Cities`}/></Field></div>{service.workflow==='inspection'&&<Field label="Seller or vehicle access contact *"><Input value={seller} onChange={e=>setSeller(e.target.value)} placeholder="Name, contact number and access instructions"/></Field>}{service.workflow==='dispatch'&&<><p className="notice">Demo dispatch only. This does not contact roadside assistance. If you are in immediate danger, contact local emergency services.</p><Field label="Tow destination or on-site assistance *"><Input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Destination address or On-site assistance"/></Field></>}<Field label={service.workflow==='estimate'?'Symptoms and requested work':'Anything we should know?'}><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe warning lights, vehicle condition or access needs." maxLength={2000}/></Field></div>}
 {step===2&&<div className="stack"><div className="two-col"><Field label="Date"><Input type="date" min={day()} value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Team member"><Choice value={staff} onChange={setStaff} options={provider.staff}/></Field></div><p className="muted">Twin Cities time · {service.duration} minute service + {provider.buffer} minute buffer</p><div className="slot-grid">{slots.map(t=><button className={time===t?'selected':''} key={t} onClick={()=>setTime(t)}>{t}</button>)}</div>{!slots.length&&<p className="notice">No times available. Choose another date or team member.</p>}<p className="muted">{service.workflow==='appointment'?'This time is reserved when you confirm.':'This is a preferred time. The business must confirm availability before scheduling.'}</p></div>}
 {step===3&&<div className="stack"><div className="summary-card"><h3>{service.name}</h3><p><Car size={17}/>{vehicleName(state.vehicles.find(v=>v.id===vehicle))}</p><p><CalendarDays size={17}/>{date} at {time} · {staff}</p><p><ClipboardCheck size={17}/>{provider.mobile?address:provider.name+' · '+provider.area}</p><div className="total"><span>{service.workflow==='estimate'?'Consultation price':'Service price'}</span><strong>{money(service.price)}</strong></div><div className="row"><span>Tovant booking fee</span><strong>$0</strong></div></div><p className="notice">Pay the business directly. No card is charged in this demo. You can cancel before work starts; no cancellation fee is simulated. {service.workflow==='estimate'?'Approve an itemized estimate before authorizing any repairs.':''}</p>{notes&&<p>{notes}</p>}</div>}
 {error&&<p role="alert" className="error">{error}</p>}<div className="modal-footer">{step>0?<Button variant="outline" onClick={()=>setStep(step-1)}>Back</Button>:role==='provider'?<Button variant="outline" onClick={onClose}>Cancel</Button>:<Button variant="outline" disabled={busy} onClick={async()=>{if(await act('draft',{id:draft?.id,serviceId,notes,vehicleId:vehicle,date,time,staff,address,zip,seller,destination},undefined,provider.id))onClose();}}>Save draft</Button>}<Button disabled={busy} onClick={step===3?confirm:next}>{busy?'Saving…':step===3?(service.workflow==='appointment'?'Confirm booking':'Send request'):'Continue'}</Button></div></>}
 </Modal>;
}
