import React from 'react';
import {useDemo} from '../../components/tovant/context';
import {available,day,vehicleName} from '../../lib/tovant/model';
import {directory} from '../data/directory';
import {emailTaken,DEMO_ACCOUNTS} from '../data/accounts';
import {toast} from 'sonner';
const categoryMap={'Mechanics & mobile':'Mechanics and mobile','Detail & ceramic':'Detail and ceramic','Tires & alignment':'Tires and alignment','Brakes & suspension':'Brakes and suspension','Body & paint':'Body work and paint','Tint & wraps':'Tint and wraps','Audio & electronics':'Audio and electronics','EV & hybrid':'EV and hybrid'};
const statusMap={requested:'open',awaiting_approval:'quoted',scheduled:'booked',in_progress:'booked',en_route:'booked',arrived:'booked',completed:'completed',cancelled:'passed'};
const windowOf=time=>Number(time?.split(':')[0])<11?'morning':Number(time?.split(':')[0])<14?'midday':'afternoon';
export function useBridge(api){
 const demo=useDemo();const {state:s,customerId,providerId,act}=demo;const current=s.customers.find(c=>c.id===customerId)||s.customers[0];const provider=s.providers.find(p=>p.id===providerId)||s.providers[0];
 React.useEffect(()=>{if(api.session?.role&&api.session.role!=='guest'){demo.setRole(api.session.role==='owner'?'customer':api.session.role);if(api.session.shopId)demo.setProviderId(api.session.shopId);}},[api.session?.role,api.session?.shopId]);
 const shops=s.providers.map(p=>{const base=directory.find(v=>v.id===p.id)||{};return {...base,id:p.id,name:p.name,mode:p.mobile?'Comes to you':'Drop off',rating:p.rating,jobCount:p.reviews,price:p.services[0].price,slot:'This week',laborRate:base.laborRate||'$120 / hr',badge:p.mobile?'COMES TO YOU':'DROP OFF',short:base.short||p.bio,note:base.note||p.bio,trades:base.trades||p.services.map(v=>categoryMap[v.category]||v.category),services:base.services||[],jobTypes:base.jobTypes||[],zips:base.zips||[p.zip,'55407'],languages:base.languages||['English'],vetted:p.verified,pending:!p.verified,accepting:p.accepting,area:p.area,distance:p.distance,lat:base.lat||44.948,lng:base.lng||-93.260};});
 const row=j=>({id:j.id,job:j.service.name,car:vehicleName(s.vehicles.find(v=>v.id===j.vehicleId)),shopId:j.providerId,shop:s.providers.find(p=>p.id===j.providerId)?.name,when:j.date+' · '+j.time,slot:j.time,date:j.date,time:j.time,window:windowOf(j.time),mode:s.providers.find(p=>p.id===j.providerId)?.mobile?'mobile':'shop',status:statusMap[j.status],domainStatus:j.status,price:j.total,note:j.notes,zip:j.zip,ownerName:s.customers.find(c=>c.id===j.customerId)?.name,phone:s.customers.find(c=>c.id===j.customerId)?.phone,address:j.address,ago:'Saved request',distance:(s.providers.find(p=>p.id===j.providerId)?.distance||0)+' mi',median:j.total,photos:(j.photos||[]).map(p=>'/api/media?key='+encodeURIComponent(p.key)),sentAt:Date.parse(j.timeline[0]?.at)||Date.now()});
 const mine=s.jobs.filter(j=>j.customerId===customerId);const company=s.jobs.filter(j=>j.providerId===providerId);const bookings=mine.filter(j=>['scheduled','in_progress','en_route','arrived','completed'].includes(j.status)).map(j=>({...row(j),vehicle:vehicleName(s.vehicles.find(v=>v.id===j.vehicleId)),slot:j.date+' · '+j.time}));
 const session={...api.session,...(api.session.role==='owner'?{name:current.name,email:current.email}:api.session.role==='provider'?{shopId:providerId,shop:provider.name}:{} )};
 const dashboard={...api.state.dashboard,shop:provider.name,capacity:{...api.state.dashboard.capacity,accepting:provider.accepting},queue:company.filter(j=>j.status==='requested').map(row),sentQuotes:company.filter(j=>j.status==='awaiting_approval').map(row),jobs:company.filter(j=>!['requested','awaiting_approval','cancelled'].includes(j.status)).map(j=>({...row(j),status:['en_route','arrived'].includes(j.status)?'in_progress':j.status,mode:s.providers.find(p=>p.id===j.providerId)?.mobile?'MOBILE':'IN SHOP'})),payouts:[{id:'direct',week:'Direct payments',amount:company.filter(j=>j.paidAt).reduce((v,j)=>v+j.total,0),jobs:company.filter(j=>j.paidAt).length,status:'cleared'}],holds:s.blocks.filter(b=>b.providerId===providerId).map(b=>({...b,window:windowOf(b.time)}))};
 const jobThreads=(session.role==='provider'?company:mine).map(j=>({id:j.id,shopId:j.providerId,shop:s.providers.find(p=>p.id===j.providerId)?.name,peer:s.customers.find(c=>c.id===j.customerId)?.name,lines:j.messages.map(m=>({from:m.role==='provider'?'shop':'owner',body:m.text,at:Date.parse(m.at)}))}));
 const messages=[...jobThreads,...api.messages.filter(t=>!jobThreads.some(j=>j.id===t.id))];
 const linked={...api.state,ownerRequests:mine.map(row),bookings,lastBooking:bookings[0]||null,shops,session,dashboard,owner:{...api.state.owner,name:current.name,email:current.email,phone:current.phone,vehicles:s.vehicles.filter(v=>v.customerId===customerId).map((v,i)=>[vehicleName(v),'MN · 55407',v.mileage.toLocaleString()+' mi',i===0])},provider:{...api.state.provider,name:provider.name,about:provider.bio}};
 const login=account=>{api.login(account);demo.setRole(account.role==='owner'?'customer':account.role);if(account.shopId)demo.setProviderId(account.shopId);const c=s.customers.find(c=>c.email===account.email);if(c)demo.setCustomerId(c.id);};
 const enterDemo=role=>login(DEMO_ACCOUNTS.find(a=>a.role===role));
 async function send(choices,extras={}){
  const draft={...api.requestDraft,...extras};const vehicle=s.vehicles.find(v=>v.customerId===customerId&&String(draft.vehicle||'').includes(vehicleName(v)))||s.vehicles.find(v=>v.customerId===customerId);if(!vehicle){toast.error('Add a vehicle in My garage before sending a request.');return false;}
  const sent=[];
  for(const shop of choices){const p=s.providers.find(p=>p.id===shop.id);if(!p)continue;const issue=Array.isArray(draft.issues)?draft.issues.join(' '):String(draft.issues||'');const service=p.services.find(v=>/oil/i.test(issue)&&/oil/i.test(v.name))||p.services[0];let date=/^\d{4}-\d{2}-\d{2}$/.test(draft.date||'')?draft.date:day(1);if(date<day())date=day(1);const slots=Array.from({length:(p.close-p.open)*2},(_,i)=>String(p.open+Math.floor(i/2)).padStart(2,'0')+':'+(i%2?'30':'00'));const requested=String(draft.slot||'').match(/^(\d{1,2})\s*(AM|PM)$/i);const preferred=requested?String((Number(requested[1])%12)+(requested[2].toUpperCase()==='PM'?12:0)).padStart(2,'0')+':00':'';const ordered=[preferred,...slots.filter(t=>windowOf(t)===(draft.windowId||'morning'))].filter(Boolean);const time=ordered.find(t=>available(s,p,date,t,service.duration,p.staff[0],'',vehicle.id));if(!time)continue;
   const ok=await act('book',{requestOnly:true,serviceId:service.id,customerId,vehicleId:vehicle.id,date,time,staff:p.staff[0],address:draft.address||api.state.owner.home||'Demo address, Minneapolis',zip:draft.zip||'55407',notes:draft.describe||draft.note||draft.notes||issue,seller:service.workflow==='inspection'?(draft.seller||'Confirm seller access through job messages'):'',destination:service.workflow==='dispatch'?(draft.destination||'On-site assistance'):''},undefined,p.id);if(ok)sent.push(p.id);
  }
  if(sent.length)api.saveDraft({...draft,sentTo:[...new Set([...(draft.sentTo||[]),...sent])]});else toast.error('No matching provider has an opening right now. Try another service or date.');return sent.length>0;
 }
 const parseVehicle=row=>{const match=String(row[0]).match(/^(\d{4})\s+(\S+)\s+(.+)$/);if(!match)throw new Error('Use year, make and model, for example 2021 Audi Q5.');return {year:match[1],make:match[2],model:match[3],mileage:Number(String(row[2]||'0').replace(/[^0-9]/g,''))||0};};
 return {...api,state:linked,shops,session,messages,ownerRequests:mine.map(row),bookings,lastBooking:bookings[0]||null,login,enterDemo,
  async registerOwner(fields){
   if(emailTaken(fields.email,api.state.accounts||[])||s.customers.some(c=>c.email.toLowerCase()===fields.email.toLowerCase()))return {ok:false,error:'That email already exists. Sign in instead.'};
   let vehicle;try{if(fields.vehicle)vehicle=parseVehicle([fields.vehicle,'','0']);}catch(e){return {ok:false,error:e.message};}
   const id=crypto.randomUUID();const ok=await act('register_owner',{id,name:fields.name,email:fields.email,phone:fields.phone||'',vehicle});if(!ok)return {ok:false,error:'Could not create the demo profile.'};
   api.registerOwner(fields);demo.setCustomerId(id);demo.setRole('customer');
   return {ok:true};
  },
  async registerProvider(fields){
   if(emailTaken(fields.email,api.state.accounts||[]))return {ok:false,error:'That email already exists. Sign in instead.'};
   const id=fields.shop.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const trade=fields.trades?.[0]||'Mechanics and mobile';const category=Object.entries(categoryMap).find(([,v])=>v===trade)?.[0]||'Mechanics & mobile';const workflow=/detail|tint|glass|tire/i.test(trade)?'appointment':/inspect/i.test(trade)?'inspection':'estimate';
   const ok=await act('onboard',{id,name:fields.shop,area:'Twin Cities',zip:fields.zip,mobile:/mobile|come to/i.test(fields.how),category,workflow,serviceName:workflow==='appointment'?'Service appointment':workflow==='inspection'?'Vehicle inspection':'Diagnostic assessment',price:100,duration:60});if(!ok)return {ok:false,error:'Could not create this business. Check the name and Twin Cities ZIP.'};
   api.registerProvider(fields);demo.setProviderId(id);demo.setRole('provider');return {ok:true};
  },
  async setOwner(partial){try{const ok=await act('profile',{name:partial.name||current.name,email:partial.email||current.email,phone:partial.phone??current.phone,...(partial.vehicles?{vehicles:partial.vehicles.map(parseVehicle)}:{})});if(ok)api.setOwner(partial);return ok;}catch(e){alert(e.message);return false;}},
  logout(){demo.setRole('customer');api.logout();},
  async sendMessage(id,shop,text,from,peer){const j=s.jobs.find(j=>j.id===id);if(!j)return api.sendMessage(id,shop,text,from,peer);const ok=await act('message',{text},j.id,j.providerId);return {ok,error:ok?'':'Message could not be saved. Please retry.'};},
  sendToShop:(shop,extras)=>send([shop],extras),sendToShops:send,
  async bookRequest(id){return act('transition',{status:'scheduled'},String(id),s.jobs.find(j=>j.id===String(id))?.providerId);},
  async sendQuote(id,price){const j=s.jobs.find(j=>j.id===String(id));if(!j)return false;if(j.service.workflow!=='estimate')return act('transition',{status:'scheduled'},j.id,j.providerId);return act('estimate',{lines:[{description:j.service.name,quantity:1,price:Number(price)}]},j.id,j.providerId);},
  passRequest:(id,reason)=>act('transition',{status:'cancelled',reason},String(id),providerId),
  async advanceJob(id){const j=s.jobs.find(j=>j.id===String(id));if(!j)return false;const next=j.status==='scheduled'?(provider.mobile?'en_route':'in_progress'):j.status==='en_route'?'arrived':j.status==='arrived'&&j.service.workflow!=='dispatch'?'in_progress':'completed';return act('transition',{status:next},j.id,j.providerId);},
  async setCapacity(cap){const ok=await act('provider',{name:provider.name,bio:provider.bio,accepting:cap.accepting,buffer:provider.buffer,radius:provider.radius,open:provider.open,close:provider.close,staff:provider.staff});if(ok)api.setCapacity(cap);return ok;},
  toggleHold(date,window){const time={morning:'08:00',midday:'11:00',afternoon:'14:00'}[window];const exists=s.blocks.find(b=>b.providerId===providerId&&b.date===date&&b.time===time);return exists?act('unblock',{id:exists.id}):act('block',{date,time,duration:180,staff:provider.staff[0]});},
  async setProvider(partial){api.setProvider(partial);return act('provider',{name:partial.name||provider.name,bio:partial.about||provider.bio,accepting:provider.accepting,buffer:provider.buffer,radius:Number(String(partial.radius||provider.radius).match(/\d+/)?.[0])||provider.radius,open:provider.open,close:provider.close,staff:provider.staff});},
  async decideCredential(id,outcome,reason){api.decideCredential(id,outcome,reason);const record=api.state.verifyQueue.find(v=>v.id===id);const p=s.providers.find(p=>p.name===record?.shop);if(p)await act('verify',{verified:outcome==='verified'},undefined,p.id);},
 };
}
